/**
 * Utility to generate product codes with brand-based prefixes
 * 
 * Generates codes in format: [BRAND_PREFIX]-[SEQUENTIAL_NUMBER]
 * Examples: BOS-001, KAY-002, REN-003
 */

/**
 * Extract a 3-character prefix from a brand name
 * @param brand - Brand name (e.g., "BOSCH", "Kayaba", "Renault")
 * @returns 3-character uppercase prefix
 */
export function getBrandPrefix(brand?: string | null): string {
    if (!brand || brand.trim() === '') {
        return 'GEN'; // GENeric for products without brand
    }

    const cleanBrand = brand.trim().toUpperCase();

    // Special mappings for common brands
    const brandMappings: Record<string, string> = {
        'BOSCH': 'BOS',
        'KAYABA': 'KAY',
        'RENAULT': 'REN',
        'TOYOTA': 'TOY',
        'NISSAN': 'NIS',
        'HONDA': 'HON',
        'CHEVROLET': 'CHE',
        'FORD': 'FOR',
        'VOLKSWAGEN': 'VW',
        'VW': 'VW',
        'HYUNDAI': 'HYU',
        'KIA': 'KIA',
        'MITSUBISHI': 'MIT',
        'SUZUKI': 'SUZ',
        'MAZDA': 'MAZ',
        'SUBARU': 'SUB',
        'ISUZU': 'ISU',
        'VOLVO': 'VOL',
        'BMW': 'BMW',
        'MERCEDES': 'MER',
        'MERCEDES-BENZ': 'MER',
        'AUDI': 'AUD',
        'PEUGEOT': 'PEU',
        'CITROEN': 'CIT',
        'FIAT': 'FIA',
        'JEEP': 'JEE',
        'LAND ROVER': 'LRO',
        'DEFENDER': 'DEF',
        'RANGE ROVER': 'RRO',
        'SACHS': 'SAC',
        'MONROE': 'MON',
        'NGK': 'NGK',
        'DENSO': 'DEN',
        'WABCO': 'WAB',
        'FERODO': 'FER',
        'BREMBO': 'BRE',
        'GATES': 'GAT',
        'DAYCO': 'DAY',
        'MAHLE': 'MAH',
        'MANN': 'MAN',
        'VALEO': 'VAL',
        'LUK': 'LUK',
        'SKF': 'SKF',
        'INA': 'INA',
        'CONTINENTAL': 'CON',
        'GOODYEAR': 'GDY',
        'BRIDGESTONE': 'BRI',
        'DUNLOP': 'DUN',
        'MICHELIN': 'MIC',
        'PIRELLI': 'PIR',
        'YOKOHAMA': 'YOK',
        'HANKOOK': 'HAN',
        'KUMHO': 'KUM',
        'GENERICO': 'GEN',
        'GENERICA': 'GEN',
        'AFTERMARKET': 'AFT',
        'ALTERNATIVO': 'ALT',
        'ORIGINAL': 'ORI',
    };

    // Check for exact match in mappings
    if (brandMappings[cleanBrand]) {
        return brandMappings[cleanBrand];
    }

    // Check for partial matches (for brands like "BOSCH AUTOMOTIVE")
    for (const [key, value] of Object.entries(brandMappings)) {
        if (cleanBrand.startsWith(key) || cleanBrand.includes(key)) {
            return value;
        }
    }

    // Default: take first 3 consonants, or first 3 characters
    const consonants = cleanBrand.replace(/[AEIOU\s\-\.]/g, '');
    if (consonants.length >= 3) {
        return consonants.slice(0, 3);
    }

    // If not enough consonants, use first 3 characters
    return cleanBrand.replace(/[\s\-\.]/g, '').slice(0, 3).padEnd(3, 'X');
}

/**
 * Generate a full product code with brand prefix and sequential number
 * @param brand - Brand name
 * @param sequentialNumber - Sequential number for this brand
 * @returns Full product code (e.g., "BOS-001")
 */
export function generateProductCode(brand: string | null | undefined, sequentialNumber: number): string {
    const prefix = getBrandPrefix(brand);
    const paddedNumber = String(sequentialNumber).padStart(3, '0');
    return `${prefix}-${paddedNumber}`;
}

/**
 * Extract the brand prefix from an existing product code
 * @param code - Product code (e.g., "BOS-001")
 * @returns The prefix part or null if not a valid format
 */
export function extractPrefixFromCode(code: string): string | null {
    const match = code.match(/^([A-Z]{2,4})-\d+$/);
    return match ? match[1] : null;
}

/**
 * Check if a code is in the auto-generated format
 * @param code - Product code to check
 * @returns true if code matches [PREFIX]-[NUMBER] format
 */
export function isAutoGeneratedCode(code: string): boolean {
    return /^[A-Z]{2,4}-\d{3,}$/.test(code);
}
