'use client';

import { useState, useEffect, useCallback } from 'react';
import { Product } from '@/types';
import { Save, Plus, Wand2, Package, Tag, Box, DollarSign, Info, LayoutGrid, Warehouse, Barcode, ChevronRight, Loader2, MapPin } from 'lucide-react';
import { SupplierService } from '@/services/SupplierService';
import { CategoryService } from '@/services/CategoryService';
import { BrandService } from '@/services/BrandService';
import { OriginService } from '@/services/OriginService';
import { InventoryService } from '@/services/InventoryService';
import { Supplier, Category, Brand, Origin } from '@/types';
import ImageUpload from '@/components/inventory/ImageUpload';
import CategoryModal from '@/components/modals/CategoryModal';
import BrandModal from '@/components/modals/BrandModal';
import OriginModal from '@/components/modals/OriginModal';
import SupplierModal from '@/components/modals/SupplierModal';
import { useBranch } from '@/contexts/BranchContext';
import { useAuth } from '@/contexts/AuthContext';
import { logAdminAction } from '@/lib/audit';
import NumericInput from '@/components/common/NumericInput';
import { toast } from 'sonner';
import clsx from 'clsx';
import { isAutoGeneratedCode } from '@/utils/productCodeGenerator';

interface ProductFormData {
    codigo: string;
    nombre: string;
    categoria: string;
    costo: number;
    stock: number;
    minStock: number;
    imagenUrl: string;
    precio: number;
    precioMayorista?: number;
    precioSinFactura?: number;
    precioConFactura?: number;
    marca?: string;
    unidad: string;
    origen?: string;
    descripcion?: string;
    codigoOE?: string;
    codigoFabrica?: string;
    supplierId: string;
    barcode: string;
    ubicacionFisica: string;
}

interface ProductFormProps {
    initialData?: Partial<Product> | null;
    onSubmit: (data: Omit<Product, 'id'>) => Promise<void>;
    onCancel: () => void;
    isLoading: boolean;
}
// Suite Pro v4.0 Precision Components (Outside for stability)
const LabelV2 = ({ children, icon: Icon }: { children: React.ReactNode, icon?: React.ElementType }) => (
    <label className="flex items-center gap-2 text-[9px] font-black uppercase tracking-[0.2em] text-slate-400 dark:text-slate-500 mb-2 ml-1">
        {Icon && <Icon size={12} strokeWidth={2.5} className="text-yellow-500" />}
        {children}
    </label>
);

const InputV2 = (props: React.InputHTMLAttributes<HTMLInputElement>) => (
    <input 
        {...props}
        className={clsx(
            "w-full h-11 px-4 rounded-xl border border-slate-200 dark:border-white/10 bg-white dark:bg-black/40 text-xs font-bold text-slate-900 dark:text-white focus:border-yellow-500 dark:focus:border-[#FFD700]/50 transition-all outline-none placeholder:text-slate-400 dark:placeholder:text-slate-600 shadow-sm",
            props.className
        )}
    />
);

const SectionV2 = ({ title, icon: Icon, children, className }: { title: string, icon: React.ElementType, children: React.ReactNode, className?: string }) => (
    <div className={clsx("bg-white dark:bg-[#111827] rounded-3xl border border-slate-200 dark:border-white/10 shadow-xl overflow-hidden", className)}>
        <div className="px-6 py-4 border-b border-slate-100 dark:border-white/10 flex items-center gap-3 bg-slate-900 dark:bg-black">
            <Icon size={16} strokeWidth={3} className="text-yellow-500" />
            <h3 className="font-black text-[10px] uppercase tracking-[0.3em] text-white">{title}</h3>
        </div>
        <div className="p-8">
            {children}
        </div>
    </div>
);

export default function ProductForm({ initialData, onSubmit, onCancel, isLoading }: ProductFormProps) {
    const { currentBranch, isHQ } = useBranch();
    const { user, role } = useAuth();
    const isGerente = role === 'GERENTE';
    const canEditMaster = isGerente && isHQ;
    // En modo edición el stock NUNCA se modifica aquí — solo vía Ajuste de Stock
    const isEditing = !!initialData?.id && !initialData.id.startsWith('virtual-');
    const [formData, setFormData] = useState<ProductFormData>({
        codigo: '',
        nombre: '',
        categoria: 'General',
        costo: 0,
        stock: 0,
        minStock: 5,
        imagenUrl: '',
        codigoOE: '',
        codigoFabrica: '',
        origen: '',
        marca: '',
        descripcion: '',
        precioMayorista: 0,
        precioSinFactura: 0,
        precioConFactura: 0,
        supplierId: '',
        barcode: '',
        ubicacionFisica: '',
        unidad: 'PZA',
        precio: 0,
    });

    const [suppliers, setSuppliers] = useState<Supplier[]>([]);
    const [categories, setCategories] = useState<Category[]>([]);
    const [brands, setBrands] = useState<Brand[]>([]);
    const [origins, setOrigins] = useState<Origin[]>([]);
    const [isCategoryModalOpen, setIsCategoryModalOpen] = useState(false);
    const [isBrandModalOpen, setIsBrandModalOpen] = useState(false);
    const [isOriginModalOpen, setIsOriginModalOpen] = useState(false);
    const [isSupplierModalOpen, setIsSupplierModalOpen] = useState(false);
    const [isGeneratingCode, setIsGeneratingCode] = useState(false);

    useEffect(() => {
        SupplierService.getSuppliers(currentBranch?.id).then(setSuppliers);
        
        // Merge managed categories with dynamic categories from products
        const loadCategories = async () => {
            const managed = await CategoryService.getCategories();
            const usedNames = await InventoryService.getUniqueCategories(currentBranch?.id || '');
            
            // Avoid duplicates (Prefer managed ones)
            const managedNames = new Set(managed.map(c => c.nombre.toLowerCase()));
            const dynamicCategories = usedNames
                .filter(name => !managedNames.has(name.toLowerCase()))
                .map(name => ({ id: name, nombre: name }));
            
            setCategories([...managed, ...dynamicCategories] as Category[]);
        };
        
        loadCategories();

        // Merge managed brands with dynamic brands from products
        const loadBrands = async () => {
            const managed = await BrandService.getBrands();
            const usedNames = await InventoryService.getUniqueBrands(currentBranch?.id || '');
            const managedNames = new Set(managed.map(b => b.nombre.toUpperCase()));
            const dynamicBrands = usedNames
                .filter(name => !managedNames.has(name.toUpperCase()))
                .map(name => ({ id: `dyn-${name}`, nombre: name }));
            setBrands([...managed, ...dynamicBrands] as Brand[]);
        };
        loadBrands();

        // Merge managed origins with dynamic origins from products
        const loadOrigins = async () => {
            const managed = await OriginService.getOrigins();
            const usedNames = await InventoryService.getUniqueOrigins(currentBranch?.id || '');
            const managedNames = new Set(managed.map(o => o.nombre.toUpperCase()));
            const dynamicOrigins = usedNames
                .filter(name => !managedNames.has(name.toUpperCase()))
                .map(name => ({ id: `dyn-${name}`, nombre: name }));
            setOrigins([...managed, ...dynamicOrigins] as Origin[]);
        };
        loadOrigins();
    }, [currentBranch?.id]);

    useEffect(() => {
        if (initialData) {
            setTimeout(() => {
                setFormData({
                    codigo: initialData.codigo || '',
                    nombre: initialData.nombre || '',
                    categoria: initialData.categoria || 'General',
                    costo: initialData.costo || 0,
                    stock: initialData.stock || 0,
                    minStock: initialData.minStock || 5,
                    imagenUrl: initialData.imagenUrl || '',
                    precio: initialData.precio || initialData.precioConFactura || 0,
                    precioMayorista: initialData.precioMayorista || 0,
                    precioSinFactura: initialData.precioSinFactura || initialData.precio || 0,
                    precioConFactura: initialData.precioConFactura || initialData.precio || 0,
                    marca: initialData.marca || '',
                    unidad: initialData.unidad || 'PZA',
                    descripcion: initialData.descripcion || '',
                    codigoOE: initialData.codigoOE || '',
                    codigoFabrica: initialData.codigoFabrica || '',
                    origen: initialData.origen || '',
                    supplierId: initialData.supplierId || '',
                    barcode: initialData.barcode || '',
                    ubicacionFisica: initialData.ubicacionFisica || '',
                });
            }, 0);
        }
    }, [initialData]);

    const generateCodeFromBrand = useCallback(async () => {
        setIsGeneratingCode(true);
        try {
            const code = await InventoryService.getNextBrandCode(formData.marca || '');
            setFormData(prev => ({ ...prev, codigo: code }));
        } catch {
            // Silent: code generation is non-critical
        } finally {
            setIsGeneratingCode(false);
        }
    }, [formData.marca]);

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        
        // Validación de precios: no permitir vender por debajo del costo
        const costo = Number(formData.costo) || 0;
        const precioConFactura = Number(formData.precioConFactura) || 0;
        const precioSinFactura = Number(formData.precioSinFactura) || 0;
        const precioMayorista = Number(formData.precioMayorista) || 0;

        if (costo < 0 || precioConFactura < 0 || precioSinFactura < 0 || precioMayorista < 0) {
            toast.error('Los precios y costos no pueden ser negativos');
            return;
        }

        if (costo > 0 && precioConFactura > 0 && precioConFactura < costo) {
            toast.error(`El precio con factura (Bs. ${precioConFactura}) no puede ser menor al costo (Bs. ${costo})`);
            return;
        }

        if (costo > 0 && precioSinFactura > 0 && precioSinFactura < costo) {
            toast.error(`El precio sin factura (Bs. ${precioSinFactura}) no puede ser menor al costo (Bs. ${costo})`);
            return;
        }

        if (costo > 0 && precioMayorista > 0 && precioMayorista < costo) {
            toast.error(`El precio mayorista (Bs. ${precioMayorista}) no puede ser menor al costo (Bs. ${costo})`);
            return;
        }

        if (initialData?.id) {
            const oldPrice = Number(initialData.precioConFactura) || 0;
            const newPrice = Number(formData.precioConFactura) || 0;
            if (oldPrice !== newPrice) {
                await logAdminAction(
                    user?.uid || '?',
                    user?.email || '?',
                    'PRICE_CHANGE',
                    initialData.id,
                    currentBranch?.id || 'GLOBAL',
                    `Precio: Bs. ${oldPrice} -> Bs. ${newPrice} (${formData.nombre})`
                );
            }
        }

        const sanitized: Omit<Product, 'id'> = {
            ...formData,
            stock: Number(formData.stock) || 0,
            minStock: Number(formData.minStock) || 0,
            precio: Number(formData.precio) || 0,
            costo: Number(formData.costo) || 0,
        } as Omit<Product, 'id'>;
        await onSubmit(sanitized);
    };

    const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
        const { name, value, type } = e.target;
        
        let finalValue: string | number = value;

        if (type === 'number') {
            // Remove leading zeros (e.g., '0575' -> '575')
            // Don't remove if it's just '0' or '0.something'
            const cleaned = value.replace(/^0+(?=\d)/, '');
            finalValue = cleaned === '' ? 0 : parseFloat(cleaned);
        }

        setFormData(prev => ({
            ...prev,
            [name]: finalValue
        }));
    };

    const handleNumericField = (name: string) => (val: string) => {
        setFormData(prev => ({ ...prev, [name]: val === '' ? 0 : parseFloat(val) }));
    };

    const isCodeAutoGenerated = isAutoGeneratedCode(formData.codigo);

    return (
        <>
            <form onSubmit={handleSubmit} className="space-y-8 max-w-6xl mx-auto pb-32 animate-in fade-in slide-in-from-bottom-5 duration-700">
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                    {/* Primary Column */}
                    <div className="lg:col-span-2 space-y-8">
                        <SectionV2 title="Identidad del Producto" icon={Package}>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                <div className="md:col-span-2">
                                    <LabelV2 icon={Tag}>Nombre Comercial / Técnico</LabelV2>
                                    <InputV2
                                        name="nombre"
                                        value={formData.nombre}
                                        onChange={handleChange}
                                        required
                                        disabled={!canEditMaster}
                                        placeholder="Ej. Kit de Embrague Renault Logan 1.6"
                                        className={clsx("text-lg", !canEditMaster && "opacity-60 bg-slate-50 dark:bg-[#111827]/50 cursor-not-allowed")}
                                    />
                                </div>
                                <div className="min-w-0">
                                    <LabelV2 icon={Barcode}>Identificador Único</LabelV2>
                                    <div className="flex gap-2 min-w-0">
                                        <input
                                            name="codigo"
                                            value={formData.codigo}
                                            onChange={handleChange}
                                            required
                                            readOnly={isCodeAutoGenerated || !canEditMaster}
                                            className={clsx(
                                                "flex-1 h-11 px-4 rounded-xl border border-slate-200 dark:border-white/10 bg-white dark:bg-black/40 text-xs font-black text-slate-900 dark:text-white focus:border-yellow-500 outline-none font-mono tracking-widest shadow-sm",
                                                (isCodeAutoGenerated || !canEditMaster) && "opacity-60 bg-slate-50 dark:bg-[#111827]/50 cursor-not-allowed"
                                            )}
                                            placeholder="RT-000"
                                        />
                                        {canEditMaster && (
                                            <button
                                                type="button"
                                                onClick={generateCodeFromBrand}
                                                disabled={isGeneratingCode || !formData.marca?.trim()}
                                                className="shrink-0 px-3 h-11 bg-slate-900 dark:bg-white/5 text-white dark:text-slate-400 border border-transparent dark:border-white/10 rounded-xl hover:bg-black dark:hover:bg-white/10 transition-all flex items-center gap-1.5 text-[10px] font-black uppercase tracking-widest disabled:opacity-20 active:scale-95 shadow-lg shadow-black/10 select-none"
                                            >
                                                <Wand2 size={14} strokeWidth={3} className={isGeneratingCode ? 'animate-spin text-yellow-500' : 'text-yellow-500'} />
                                                <span className="hidden sm:inline">{isGeneratingCode ? '...' : 'Generar'}</span>
                                            </button>
                                        )}
                                    </div>
                                    <p className="text-[9px] font-black text-slate-400 dark:text-slate-500 mt-2 px-1 uppercase tracking-widest opacity-60 italic">Se requiere marca para auto-generar</p>
                                </div>
                                <div>
                                    <LabelV2 icon={LayoutGrid}>Categoría Operativa</LabelV2>
                                    <div className="flex gap-2">
                                        <select
                                            name="categoria"
                                            value={formData.categoria}
                                            onChange={handleChange}
                                            disabled={!canEditMaster}
                                            className={clsx(
                                                "flex-1 h-11 px-4 rounded-xl border border-slate-200 dark:border-white/10 bg-white dark:bg-black/40 text-xs font-bold text-slate-900 dark:text-white focus:border-yellow-500 transition-all outline-none appearance-none cursor-pointer shadow-sm",
                                                !canEditMaster && "opacity-60 bg-slate-50 dark:bg-[#111827]/50 cursor-not-allowed"
                                            )}
                                        >
                                            <option value="General">General</option>
                                            {categories.map(c => (
                                                <option key={c.id} value={c.nombre}>{c.nombre}</option>
                                            ))}
                                        </select>
                                        {canEditMaster && (
                                            <button
                                                type="button"
                                                onClick={() => setIsCategoryModalOpen(true)}
                                                className="w-11 h-11 bg-white dark:bg-white/5 text-slate-400 rounded-xl hover:text-yellow-500 border border-slate-200 dark:border-white/10 transition-all flex items-center justify-center active:scale-95 shadow-sm"
                                            >
                                                <Plus size={18} strokeWidth={3} />
                                            </button>
                                        )}
                                    </div>
                                </div>
                                <div>
                                    <LabelV2 icon={Info}>Referencia OEM</LabelV2>
                                    <InputV2 name="codigoOE" value={formData.codigoOE} onChange={handleChange} disabled={!canEditMaster} placeholder="Original Equipment Manufacturer" className={!canEditMaster ? "opacity-60 cursor-not-allowed" : ""} />
                                </div>
                                <div>
                                    <LabelV2 icon={Info}>Referencia Fábrica</LabelV2>
                                    <InputV2 name="codigoFabrica" value={formData.codigoFabrica} onChange={handleChange} disabled={!canEditMaster} placeholder="Manufacturer Part Number" className={!canEditMaster ? "opacity-60 cursor-not-allowed" : ""} />
                                </div>
                                <div>
                                    <LabelV2 icon={ChevronRight}>Marca del Fabricante</LabelV2>
                                    <div className="flex gap-2">
                                        <select
                                            name="marca"
                                            value={formData.marca}
                                            onChange={handleChange}
                                            disabled={!canEditMaster}
                                            className={clsx(
                                                "flex-1 h-11 px-4 rounded-xl border border-slate-200 dark:border-white/10 bg-white dark:bg-black/40 text-xs font-bold text-slate-900 dark:text-white focus:border-yellow-500 transition-all outline-none appearance-none cursor-pointer shadow-sm uppercase",
                                                !canEditMaster && "opacity-60 bg-slate-50 dark:bg-[#111827]/50 cursor-not-allowed"
                                            )}
                                        >
                                            <option value="">— Sin marca —</option>
                                            {brands.map(b => (
                                                <option key={b.id} value={b.nombre}>{b.nombre}</option>
                                            ))}
                                        </select>
                                        {canEditMaster && (
                                            <button
                                                type="button"
                                                onClick={() => setIsBrandModalOpen(true)}
                                                className="w-11 h-11 bg-white dark:bg-white/5 text-slate-400 rounded-xl hover:text-yellow-500 border border-slate-200 dark:border-white/10 transition-all flex items-center justify-center active:scale-95 shadow-sm"
                                            >
                                                <Plus size={18} strokeWidth={3} />
                                            </button>
                                        )}
                                    </div>
                                </div>
                                <div>
                                    <LabelV2 icon={ChevronRight}>País de Origen</LabelV2>
                                    <div className="flex gap-2">
                                        <select
                                            name="origen"
                                            value={formData.origen}
                                            onChange={handleChange}
                                            disabled={!canEditMaster}
                                            className={clsx(
                                                "flex-1 h-11 px-4 rounded-xl border border-slate-200 dark:border-white/10 bg-white dark:bg-black/40 text-xs font-bold text-slate-900 dark:text-white focus:border-yellow-500 transition-all outline-none appearance-none cursor-pointer shadow-sm uppercase",
                                                !canEditMaster && "opacity-60 bg-slate-50 dark:bg-[#111827]/50 cursor-not-allowed"
                                            )}
                                        >
                                            <option value="">— Sin origen —</option>
                                            {origins.map(o => (
                                                <option key={o.id} value={o.nombre}>{o.nombre}</option>
                                            ))}
                                        </select>
                                        {canEditMaster && (
                                            <button
                                                type="button"
                                                onClick={() => setIsOriginModalOpen(true)}
                                                className="w-11 h-11 bg-white dark:bg-white/5 text-slate-400 rounded-xl hover:text-yellow-500 border border-slate-200 dark:border-white/10 transition-all flex items-center justify-center active:scale-95 shadow-sm"
                                            >
                                                <Plus size={18} strokeWidth={3} />
                                            </button>
                                        )}
                                    </div>
                                </div>
                                <div className="md:col-span-2">
                                    <LabelV2 icon={Info}>Especificaciones Adicionales</LabelV2>
                                    <textarea
                                        name="descripcion"
                                        value={formData.descripcion}
                                        onChange={handleChange}
                                        disabled={!canEditMaster}
                                        rows={3}
                                        className={clsx(
                                            "w-full rounded-xl border border-slate-200 dark:border-white/10 bg-white dark:bg-black/40 p-4 text-xs font-medium text-slate-900 dark:text-white focus:border-yellow-500 transition-all outline-none resize-none placeholder:text-slate-400 dark:placeholder:text-slate-600 shadow-sm",
                                            !canEditMaster && "opacity-60 bg-slate-50 dark:bg-[#111827]/50 cursor-not-allowed"
                                        )}
                                        placeholder="Detalles sobre compatibilidad, medidas o aplicaciones técnicas..."
                                    />
                                </div>
                            </div>
                        </SectionV2>

                        <SectionV2 title="Estructura de Costos y PVP" icon={DollarSign}>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                                {isGerente && (
                                    <div className="p-6 bg-slate-50 dark:bg-white/5 rounded-3xl border border-slate-200/60 dark:border-white/10">
                                        <LabelV2 icon={Box}>Costo de Importación / Compra</LabelV2>
                                        <div className="relative">
                                            <span className="absolute left-5 top-1/2 -translate-y-1/2 text-slate-400 font-black text-sm uppercase">Bs</span>
                                            <NumericInput
                                                name="costo"
                                                value={formData.costo}
                                                onChange={handleNumericField('costo')}
                                                className="w-full rounded-2xl bg-white dark:bg-black border-2 border-slate-200 dark:border-white/10 p-5 pl-14 text-2xl font-black text-blue-600 focus:border-blue-500 outline-none transition-all tabular-nums"
                                            />
                                        </div>
                                    </div>
                                )}
                                <div className="p-6 bg-slate-50 dark:bg-white/5 rounded-3xl border border-slate-200/60 dark:border-white/10">
                                    <LabelV2 icon={ChevronRight}>Precio Venta Mayorista</LabelV2>
                                    <div className="relative">
                                        <span className="absolute left-5 top-1/2 -translate-y-1/2 text-slate-400 font-black text-sm uppercase">Bs</span>
                                        <NumericInput
                                            name="precioMayorista"
                                            value={formData.precioMayorista ?? 0}
                                            onChange={handleNumericField('precioMayorista')}
                                            className="w-full rounded-2xl bg-white dark:bg-black border-2 border-slate-200 dark:border-white/10 p-5 pl-14 text-2xl font-black text-slate-900 dark:text-white focus:border-blue-500 outline-none transition-all tabular-nums"
                                        />
                                    </div>
                                </div>
                                <div className="p-8 bg-blue-50/50 dark:bg-blue-900/10 rounded-3xl border border-blue-200 dark:border-blue-500/20 shadow-lg shadow-blue-500/5">
                                    <LabelV2 icon={DollarSign}>Precio de Venta (Sin Factura)</LabelV2>
                                    <div className="relative mt-4">
                                        <span className="absolute left-6 top-1/2 -translate-y-1/2 text-blue-500/50 font-black text-xl">Bs</span>
                                        <NumericInput
                                            name="precioSinFactura"
                                            value={formData.precioSinFactura ?? 0}
                                            onChange={handleNumericField('precioSinFactura')}
                                            className="w-full rounded-3xl bg-white dark:bg-[#111827] border-2 border-blue-300 dark:border-blue-500/40 p-6 pl-16 text-4xl font-black text-blue-700 dark:text-blue-400 focus:border-blue-500 outline-none shadow-2xl shadow-blue-500/10 transition-all tabular-nums"
                                        />
                                    </div>
                                </div>
                                <div className="p-8 bg-amber-50/50 dark:bg-[#FFD700]/10 rounded-3xl border border-amber-200 dark:border-[#FFD700]/20 shadow-lg shadow-yellow-500/5">
                                    <LabelV2 icon={DollarSign}>Precio de Venta (Con Factura)</LabelV2>
                                    <div className="relative mt-4">
                                        <span className="absolute left-6 top-1/2 -translate-y-1/2 text-amber-500/50 font-black text-xl">Bs</span>
                                        <NumericInput
                                            name="precioConFactura"
                                            value={formData.precioConFactura ?? 0}
                                            onChange={handleNumericField('precioConFactura')}
                                            className="w-full rounded-3xl bg-white dark:bg-[#111827] border-2 border-amber-300 dark:border-[#FFD700]/40 p-6 pl-16 text-4xl font-black text-amber-600 dark:text-[#FFD700] focus:border-yellow-500 outline-none shadow-2xl shadow-yellow-500/10 transition-all tabular-nums"
                                        />
                                    </div>
                                </div>
                            </div>
                        </SectionV2>
                    </div>

                    {/* Lateral Column */}
                    <div className="space-y-8">
                        <div className="bg-slate-900 dark:bg-black/40 backdrop-blur-3xl rounded-3xl p-8 border border-white/10 shadow-2xl relative overflow-hidden group">
                           <div className="absolute inset-0 bg-linear-to-br from-blue-500/10 via-transparent to-transparent pointer-events-none" />
                           <LabelV2 icon={Package}>Visual Identity</LabelV2>
                           <div className="mt-4">
                                <ImageUpload
                                    value={formData.imagenUrl}
                                    onChange={(url) => setFormData(prev => ({ ...prev, imagenUrl: url }))}
                                    disabled={!canEditMaster}
                                />
                           </div>
                        </div>

                        <SectionV2 title="Logística y Stock" icon={Warehouse}>
                            <div className="space-y-6">
                                <div className="grid grid-cols-2 gap-4">
                                    <div className={clsx("p-6 rounded-2xl border overflow-hidden", isEditing ? "bg-slate-50 dark:bg-white/5 border-slate-200/50 dark:border-white/10/50" : "bg-slate-100 dark:bg-white/5 border-slate-200 dark:border-white/10")}>
                                        <LabelV2 icon={Box}>Unidades en Mano</LabelV2>
                                        <div className="flex items-center gap-2">
                                            <NumericInput
                                                name="stock"
                                                value={formData.stock}
                                                onChange={handleNumericField('stock')}
                                                disabled={isEditing}
                                                className={clsx("flex-1 min-w-0 w-full bg-transparent border-none focus:ring-0 outline-none text-2xl font-black px-1 py-2 tabular-nums", isEditing ? "text-slate-400 dark:text-slate-600 cursor-not-allowed" : "text-slate-900 dark:text-white")}
                                            />
                                            <select 
                                                name="unidad" 
                                                value={formData.unidad} 
                                                onChange={handleChange}
                                                disabled={!canEditMaster}
                                                className={clsx(
                                                    "shrink-0 bg-white dark:bg-white/5 rounded-xl px-2 py-2 text-[10px] font-black uppercase tracking-widest border border-slate-200 dark:border-white/10 outline-none",
                                                    !canEditMaster && "opacity-60 cursor-not-allowed"
                                                )}
                                            >
                                                <option value="PZA">PZA</option>
                                                <option value="LTS">LTS</option>
                                                <option value="KG">KG</option>
                                                <option value="SET">SET</option>
                                                <option value="PAR">PAR</option>
                                            </select>
                                        </div>
                                        {isEditing && (
                                            <p className="text-[9px] font-bold text-amber-600 dark:text-amber-400 mt-2 uppercase tracking-widest">
                                                Solo se modifica con Ajuste de Stock
                                            </p>
                                        )}
                                    </div>
                                    <div className="p-6 bg-rose-50/50 dark:bg-rose-500/5 rounded-2xl border border-rose-100 dark:border-rose-500/10 overflow-hidden">
                                        <LabelV2 icon={Info}>Alerta Stock Mínimo</LabelV2>
                                        <div className="flex items-center">
                                            <NumericInput
                                                name="minStock"
                                                value={formData.minStock}
                                                onChange={handleNumericField('minStock')}
                                                className="flex-1 min-w-0 w-full bg-transparent border-none focus:ring-0 outline-none text-2xl font-black text-rose-600 dark:text-rose-400 px-1 py-2 tabular-nums"
                                            />
                                        </div>
                                    </div>
                                </div>
                                <div>
                                    <LabelV2 icon={ChevronRight}>Proveedor Designado</LabelV2>
                                    <div className="flex gap-3">
                                        <select
                                            name="supplierId"
                                            value={formData.supplierId}
                                            onChange={handleChange}
                                            className="flex-1 rounded-2xl border-2 border-transparent bg-slate-100 dark:bg-white/5 p-4 text-xs font-black text-slate-500 dark:text-slate-400 focus:border-blue-500 focus:bg-white dark:focus:bg-black transition-all outline-none appearance-none cursor-pointer"
                                        >
                                            <option value="">Opcional: Seleccionar</option>
                                            {suppliers.map(s => (
                                                <option key={s.id} value={s.id}>{s.razonSocial}</option>
                                            ))}
                                        </select>
                                        <button
                                            type="button"
                                            onClick={() => setIsSupplierModalOpen(true)}
                                            className="p-4 bg-white dark:bg-white/5 text-slate-400 rounded-2xl hover:text-blue-500 border border-slate-200 dark:border-white/10 transition-all flex items-center justify-center active:scale-90"
                                        >
                                            <Plus size={18} strokeWidth={3} />
                                        </button>
                                    </div>
                                </div>
                                <div>
                                    <LabelV2 icon={Barcode}>Código de Barras (EAN)</LabelV2>
                                    <InputV2 name="barcode" value={formData.barcode} onChange={handleChange} placeholder="7770000000000" className="font-mono text-xs" />
                                </div>
                                <div>
                                    <LabelV2 icon={MapPin}>Ubicación Física (Estante/Posición)</LabelV2>
                                    <InputV2 name="ubicacionFisica" value={formData.ubicacionFisica} onChange={handleChange} placeholder="Ej: ESTANTE-A1" className="font-black" />
                                </div>
                            </div>
                        </SectionV2>
                    </div>
                </div>

                {/* v4.0 Precision Action Bar */}
                <div className="fixed bottom-10 left-0 right-0 lg:left-64 p-6 z-100 pointer-events-none">
                    <div className="max-w-6xl mx-auto flex justify-center">
                        <div className="bg-slate-900 dark:bg-black p-2 rounded-2xl border border-white/10 shadow-[0_32px_128px_-32px_rgba(0,0,0,0.8)] flex gap-2 pointer-events-auto ring-1 ring-white/10 animate-in slide-in-from-bottom-10 duration-700">
                            <button
                                type="button"
                                onClick={onCancel}
                                className="px-8 h-12 rounded-xl text-[9px] font-black uppercase tracking-widest text-slate-400 hover:text-white hover:bg-white/5 transition-all active:scale-95"
                            >
                                Revertir
                            </button>
                            <button
                                type="submit"
                                disabled={isLoading}
                                className="px-12 h-12 bg-yellow-500 hover:bg-yellow-400 text-black rounded-xl text-[9px] font-black uppercase tracking-[0.2em] shadow-xl shadow-yellow-500/10 flex items-center gap-3 transition-all disabled:opacity-30 active:scale-95"
                            >
                                {isLoading ? (
                                    <Loader2 className="animate-spin" size={16} strokeWidth={3} />
                                ) : (
                                    <>
                                        <Save size={16} strokeWidth={3} /> 
                                        {initialData?.id ? 'Guardar Cambios' : 'Registrar Nuevo'}
                                        <ChevronRight size={14} strokeWidth={3} className="opacity-40" />
                                    </>
                                )}
                            </button>
                        </div>
                    </div>
                </div>
            </form>

            <CategoryModal
                isOpen={isCategoryModalOpen}
                onClose={() => setIsCategoryModalOpen(false)}
                onSuccess={(cat) => {
                    setCategories(prev => [...prev, cat].sort((a, b) => a.nombre.localeCompare(b.nombre)));
                    setFormData(prev => ({ ...prev, categoria: cat.nombre }));
                }}
            />
            <BrandModal
                isOpen={isBrandModalOpen}
                onClose={() => setIsBrandModalOpen(false)}
                onSuccess={(b) => {
                    setBrands(prev => [...prev, b].sort((a, c) => a.nombre.localeCompare(c.nombre)));
                    setFormData(prev => ({ ...prev, marca: b.nombre }));
                }}
            />
            <OriginModal
                isOpen={isOriginModalOpen}
                onClose={() => setIsOriginModalOpen(false)}
                onSuccess={(o) => {
                    setOrigins(prev => [...prev, o].sort((a, c) => a.nombre.localeCompare(c.nombre)));
                    setFormData(prev => ({ ...prev, origen: o.nombre }));
                }}
            />
            <SupplierModal
                isOpen={isSupplierModalOpen}
                onClose={() => setIsSupplierModalOpen(false)}
                onSuccess={(sup) => {
                    setSuppliers(prev => [...prev, sup].sort((a, b) => a.razonSocial.localeCompare(b.razonSocial)));
                    setFormData(prev => ({ ...prev, supplierId: sup.id || '' }));
                }}
            />
        </>
    );
}
