import { describe, it, expect } from 'vitest'
import {
    getBrandPrefix,
    generateProductCode,
    extractPrefixFromCode,
    isAutoGeneratedCode,
} from '@/utils/productCodeGenerator'

describe('getBrandPrefix', () => {
    it('returns GEN for empty/null/undefined', () => {
        expect(getBrandPrefix('')).toBe('GEN')
        expect(getBrandPrefix(null)).toBe('GEN')
        expect(getBrandPrefix(undefined)).toBe('GEN')
    })

    it('returns mapped prefix for known brands', () => {
        expect(getBrandPrefix('BOSCH')).toBe('BOS')
        expect(getBrandPrefix('TOYOTA')).toBe('TOY')
        expect(getBrandPrefix('KAYABA')).toBe('KAY')
        expect(getBrandPrefix('BMW')).toBe('BMW')
        expect(getBrandPrefix('VW')).toBe('VW')
        expect(getBrandPrefix('VOLKSWAGEN')).toBe('VW')
    })

    it('matches partial brand names', () => {
        expect(getBrandPrefix('BOSCH AUTOMOTIVE')).toBe('BOS')
        expect(getBrandPrefix('TOYOTA GENUINE')).toBe('TOY')
    })

    it('falls back to first 3 consonants for unknown brands', () => {
        expect(getBrandPrefix('XYZCORP')).toBe('XYZ')
        // BRADFORD contains 'FORD' which is a known brand mapping
        expect(getBrandPrefix('QWERTZ')).toBe('QWR')
    })

    it('pads with X if not enough consonants', () => {
        expect(getBrandPrefix('AEI')).toBe('AEI')
        expect(getBrandPrefix('AO')).toBe('AOX')
    })

    it('handles whitespace and case', () => {
        expect(getBrandPrefix('  bosch  ')).toBe('BOS')
        expect(getBrandPrefix('toyota')).toBe('TOY')
    })
})

describe('generateProductCode', () => {
    it('generates code with prefix and padded number', () => {
        expect(generateProductCode('BOSCH', 1)).toBe('BOS-001')
        expect(generateProductCode('BOSCH', 42)).toBe('BOS-042')
        expect(generateProductCode('BOSCH', 999)).toBe('BOS-999')
    })

    it('handles null brand', () => {
        expect(generateProductCode(null, 5)).toBe('GEN-005')
    })
})

describe('extractPrefixFromCode', () => {
    it('extracts prefix from valid code', () => {
        expect(extractPrefixFromCode('BOS-001')).toBe('BOS')
        expect(extractPrefixFromCode('REN-042')).toBe('REN')
        expect(extractPrefixFromCode('GEN-999')).toBe('GEN')
    })

    it('returns null for invalid format', () => {
        expect(extractPrefixFromCode('BOSCH-001')).toBeNull()
        expect(extractPrefixFromCode('001')).toBeNull()
        expect(extractPrefixFromCode('')).toBeNull()
    })
})

describe('isAutoGeneratedCode', () => {
    it('returns true for valid codes', () => {
        expect(isAutoGeneratedCode('BOS-001')).toBe(true)
        expect(isAutoGeneratedCode('REN-042')).toBe(true)
        expect(isAutoGeneratedCode('GEN-9999')).toBe(true)
    })

    it('returns false for invalid codes', () => {
        expect(isAutoGeneratedCode('BOSCH-001')).toBe(false)
        expect(isAutoGeneratedCode('001')).toBe(false)
        expect(isAutoGeneratedCode('')).toBe(false)
        expect(isAutoGeneratedCode('abc-001')).toBe(false)
    })
})
